//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int sohoadon { get; set; }
        public string masanpham { get; set; }
        public string tensanpham { get; set; }
        public int soluong { get; set; }
        public decimal dongia { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual hoadon hoadon { get; set; }
    }
}
