//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class danhmucsanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhmucsanpham()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        [Required]
        [DisplayName("Mã Danh Mục")]
        public string madanhmuc { get; set; }
        [Required]
        [DisplayName("Tên Danh Mục")]
        public string tendanhmuc { get; set; }
        [Required]
        [DisplayName("Mã Danh Mục Cha")]
        public string madanhmuccha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
