//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public int sohoadon { get; set; }
        public string makhachhang { get; set; }
        public string tenkhachhang { get; set; }
        public string email { get; set; }
        public decimal sodienthoai { get; set; }
        public decimal tongiatri { get; set; }
        public string hinhthucthanhtoan { get; set; }
        public string hinhthucnhanhang { get; set; }
        public string ghichu { get; set; }
        public System.DateTime ngaygiaodich { get; set; }
        public byte trangthai { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual chitiethoadon chitiethoadon { get; set; }
    }
}
