//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class khuyenmai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyenmai()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        [Required]
        [DisplayName("Mã khuyến mãi")]
        public string makhuyenmai { get; set; }
        [Required]
        [DisplayName("Thời gian bắt đầu khuyến mãi")]
        public System.DateTime thoigianbatdau { get; set; }
        [Required]
        [DisplayName("Thời gian kết thúc khuyến mãi")]
        public System.DateTime thoigianketthuc { get; set; }
        [Required]
        [DisplayName("Nội dung")]
        public string noidung { get; set; }
        [Required]
        [DisplayName("Chi tiết")]
        public string chitiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
