//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
        }
    
        public string masanpham { get; set; }
        public string tensanpham { get; set; }
        public string madanhmuc { get; set; }
        public string loai { get; set; }
        public int soluong { get; set; }
        public decimal gia { get; set; }
        public string nhacungcap { get; set; }
        public string makhuyenmai { get; set; }
        public string mota { get; set; }
        public string lienketanh { get; set; }
        public int luotxem { get; set; }
        public System.DateTime thoigiandang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        public virtual danhmucsanpham danhmucsanpham { get; set; }
        public virtual khuyenmai khuyenmai { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
    }
}
